- name: Install required packages
  apt:
    name:
      - apache2
      - php
      - php-curl
      - php-fpm
      - php-bcmath
      - php-gd
      - php-soap
      - php-zip
      - php-mbstring
      - php-mysqlnd
      - php-xml
      - php-intl
      - unzip
    update_cache: true
    state: latest

- name: Create PrestaShop directory
  file:
    path: "{{ presta_path }}"
    owner: www-data
    group: www-data
    state: directory
    mode: '0755'

- name: Download and extract PrestaShop
  unarchive:
    src: https://github.com/PrestaShop/PrestaShop/releases/download/8.2.1/prestashop_8.2.1.zip
    dest: /tmp/
    remote_src: yes

- file:
    path: /tmp/prestashop_extracted/
    state: directory
    mode: '0755'

- name: Extract inner prestashop.zip
  unarchive:
    src: /tmp/prestashop.zip
    dest: /tmp/prestashop_extracted/
    remote_src: yes

- name: Copy PrestaShop to web root
  copy:
    src: /tmp/prestashop_extracted/
    dest: "{{ presta_path }}/"
    remote_src: yes
    owner: www-data
    group: www-data

- name: Set correct permissions on PrestaShop directory
  file:
    path: "{{ presta_path }}"
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'

- name: Add Apache vhost config
  template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/080-{{ presta_domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart apache2

- name: Enable Apache modules and site
  shell: |
    a2enmod rewrite
    a2dissite 000-default.conf
    a2ensite 080-{{ presta_domain }}
  notify: Restart apache2
