- apt:
    name:
      - apache2
      - php
      - php-curl
      - php-fpm
      - php-bcmath
      - php-gd
      - php-soap
      - php-zip
      - php-mbstring
      - php-mysqlnd
      - php-xml
      - php-intl
      - unzip
    update_cache: true
    state: latest

- file:
    path: "{{ presta_path }}"
    owner: www-data
    group: www-data
    state: directory
    mode: '0755'

- unarchive:
    src: https://github.com/PrestaShop/PrestaShop/releases/download/8.2.1/prestashop_8.2.1.zip
    dest: /tmp/
    remote_src: true

- file:
    path: /tmp/prestashop_extracted/
    state: directory
    mode: '0755'

- unarchive:
    src: /tmp/prestashop.zip
    dest: /tmp/prestashop_extracted/
    remote_src: true

- copy:
    src: /tmp/prestashop_extracted/
    dest: "{{ presta_path }}/"
    remote_src: true
    owner: www-data
    group: www-data

- file:
    path: "{{ presta_path }}"
    recurse: true
    owner: www-data
    group: www-data
    mode: '0755'

- template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/080-{{ presta_domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart apache2

- shell: |
    a2enmod rewrite
    a2dissite 000-default.conf
    a2ensite 080-{{ presta_domain }}
  notify: Restart apache2
