- name: "Setup load balancer"
  hosts: load-balancer
  become: true
  roles:
    - load-balancer

- name: "Setup mariadb"
  hosts: mariadb
  become: true
  roles:
    - mariadb

- name: "Setup wordpress"
  hosts: wordpress
  become: true
  vars:
    wp_domain: "{{ hostvars['192.168.70.68'].domain_name }}"
    wp_path: "/var/www/{{ wp_domain }}"
    wp_db_host: 192.168.70.70
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_pass: root
    wp_site_url: "http://{{ wp_domain }}"
    wp_site_title: "Mon site WordPress"
    wp_admin_user: admin
    wp_admin_password: admin
    wp_admin_email: admin@example.com
  roles:
    - wordpress

- name: "Setup prestashop"
  hosts: prestashop
  become: true
  vars:
    presta_domain: "{{ hostvars['192.168.70.69'].domain_name }}"
    presta_path: "/var/www/{{ presta_domain }}"
  roles:
    - prestashop

- name: "Déploiement du monitoring"
  hosts: all
  become: true
  roles:
    - role: monitoring
