- command: a2enmod status

- template:
    src: status.conf.j2
    dest: /etc/apache2/conf-available/status.conf
    owner: root
    group: root
    mode: '0644'

- command: a2enconf status
  notify: Restart apache2

- file:
    path: /opt/apache-exporter
    state: directory
    owner: root
    group: root
    mode: '0755'

- copy:
    src: apache/compose.yml
    dest: /opt/apache-exporter/compose.yml
    owner: root
    group: root
    mode: '0644'

- community.docker.docker_compose_v2:
    project_src: /opt/apache-exporter
    state: present
