services:
  keepalived-exporter:
    image: mehdy/keepalived-exporter:v1.7.0
    container_name: keepalived-exporter
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    environment:
      - LISTEN_ADDRESS=:9165
