services:
  apache-exporter:
    image: lusotycoon/apache-exporter:v1.0.10
    container_name: apache-exporter
    restart: unless-stopped
    network_mode: "host"
    environment:
      - APACHE_STATUS_URL=http://localhost/server-status?auto
