services:
  apache-exporter:
    image: lusotycoon/apache-exporter:v1.0.10
    container_name: apache-exporter
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - APACHE_STATUS_URL=http://host.docker.internal/server-status?auto
