services:
  mariadb-exporter:
    image: prom/mysqld-exporter:v0.17.2
    container_name: mariadb-exporter
    network_mode: host
    port: "9104:9104"
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "exporter:exporterpass@(localhost:3306)/"