name: Déploiement avec Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement Service
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - run: |
          ansible-playbook -i inventory.yml deploy.yml
