name: Maintenance

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  deploy:
    name: Maintenance
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          ansible-playbook -i inventory.yml maintenance.yml
